# Screenshot MCP Server Configuration

server:
  # Server binding configuration
  host: "localhost"
  port: 8080
  
  # Request timeout settings
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

screenshot:
  # Default image format (png, jpeg, bmp)
  default_format: "png"
  
  # Default JPEG quality (1-100)
  quality: 95
  
  # Include mouse cursor in screenshots by default
  include_cursor: false
  
  # Include window frame/border by default
  include_frame: true
  
  # Allow capturing minimized windows
  allow_minimized: true
  
  # Automatically restore minimized windows for capture
  restore_window: false
  
  # Wait time for window to become visible after restore
  wait_for_visible: "2s"
  
  # Number of retry attempts for failed captures
  retry_count: 3

chrome:
  # Chrome DevTools Protocol settings
  default_debug_port: 9222
  
  # Connection timeout for Chrome instances
  timeout: "30s"
  
  # HTTP client timeout for DevTools API
  http_timeout: "10s"
  
  # WebSocket handshake timeout
  ws_timeout: "10s"
  
  # Auto-discover Chrome instances on startup
  auto_discover: true

logging:
  # Log level: debug, info, warn, error
  level: "info"
  
  # Log format: json, console
  format: "json"
  
  # Log file path (empty for stdout only)
  file: ""
  
  # Enable request logging
  log_requests: true
  
  # Enable performance metrics logging
  log_metrics: true

security:
  # Enable CORS (for web browser access)
  enable_cors: true
  
  # Allowed origins for CORS (* for all)
  cors_origins:
    - "*"
  
  # Enable request rate limiting
  enable_rate_limit: false
  
  # Requests per minute per client
  rate_limit: 60

features:
  # Enable WebSocket streaming
  enable_streaming: true
  
  # Enable window management APIs
  enable_window_management: true
  
  # Enable Chrome integration
  enable_chrome_integration: true
  
  # Enable metrics endpoint (/metrics)
  enable_metrics: true
  
  # Enable health check endpoint (/health)
  enable_health_check: true

# Development settings
development:
  # Enable debug mode
  debug: false
  
  # Enable profiling endpoints
  enable_profiling: false
  
  # Enable additional logging
  verbose_logging: false